/*
// MUST BE X11 colors for THREE.js
var colorTable = [
      
  {"color":"AntiqueWhite",  "code":"#FAEBD7"},
  {"color":"Aquamarine",  "code":"#7FFFD4"},
  {"color":"Blue",  "code":"#0000FF"},
  {"color":"BlueViolet",  "code":"#8A2BE2"},
  {"color":"Brown", "code":"#A52A2A"},
  {"color":"CadetBlue", "code":"#5F9EA0"},
  {"color":"Chartreuse",  "code":"#7FFF00"},
  {"color":"Chocolate", "code":"#D2691E"},
  {"color":"Coral", "code":"#FF7F50"},
  {"color":"CornflowerBlue",  "code":"#6495ED"},
  {"color":"Crimson", "code":"#DC143C"},
  {"color":"Cyan",  "code":"#00FFFF"},
  {"color":"DarkGoldenrod", "code":"#B8860B"},
  {"color":"DarkGray",  "code":"#A9A9A9"},
  {"color":"DarkKhaki", "code":"#BDB76B"},
  {"color":"DarkOliveGreen",  "code":"#556B2F"},
  {"color":"DarkOrange",  "code":"#FF8C00"},
  {"color":"DarkOrchid",  "code":"#9932CC"},
  {"color":"DarkRed", "code":"#8B0000"},
  {"color":"DarkSeaGreen",  "code":"#8FBC8F"},
  {"color":"DarkTurquoise", "code":"#00CED1"},
  {"color":"DeepPink",  "code":"#FF1493"},
  {"color":"DeepSkyBlue", "code":"#00BFFF"},
  {"color":"DodgerBlue",  "code":"#1E90FF"},
  {"color":"FireBrick", "code":"#B22222"},
  {"color":"Gold",  "code":"#FFD700"},
  {"color":"Goldenrod", "code":"#DAA520"},
  {"color":"Green", "code":"#008000"},
  {"color":"GreenYellow", "code":"#ADFF2F"},
  {"color":"HotPink", "code":"#FF69B4"},
  {"color":"IndianRed", "code":"#CD5C5C"},
  {"color":"Ivory", "code":"#FFFFF0"},
  {"color":"Khaki", "code":"#F0E68C"},
  {"color":"Lavender",  "code":"#E6E6FA"},
  {"color":"LawnGreen", "code":"#7CFC00"},
  {"color":"LemonChiffon",  "code":"#FFFACD"},
  {"color":"LightCyan", "code":"#E0FFFF"},
  {"color":"LightGoldenrodYellow",  "code":"#FAFAD2"},
  {"color":"LightGreen",  "code":"#90EE90"},
  {"color":"LightPink", "code":"#FFB6C1"},
  {"color":"LightSalmon", "code":"#FFA07A"},
  {"color":"LightSeaGreen", "code":"#20B2AA"},
  {"color":"LightSteelBlue",  "code":"#B0C4DE"},
  {"color":"Lime",  "code":"#00FF00"},
  {"color":"LimeGreen", "code":"#32CD32"},
  {"color":"Magenta", "code":"#FF00FF"},
  {"color":"Maroon",  "code":"#800000"},
  {"color":"MediumAquamarine",  "code":"#66CDAA"},
  {"color":"MediumPurple",  "code":"#9370DB"},
  {"color":"MediumSeaGreen",  "code":"#3CB371"},
  {"color":"MediumSlateBlue", "code":"#7B68EE"},
  {"color":"MediumSpringGreen", "code":"#00FA9A"},
  {"color":"MediumTurquoise", "code":"#48D1CC"},
  {"color":"NavajoWhite", "code":"#FFDEAD"},
  {"color":"Olive", "code":"#808000"},
  {"color":"OliveDrab", "code":"#6B8E23"},
  {"color":"Orange",  "code":"#FFA500"},
  {"color":"OrangeRed", "code":"#FF4500"},
  {"color":"Orchid",  "code":"#DA70D6"},
  {"color":"PaleGoldenrod", "code":"#EEE8AA"},
  {"color":"PaleGreen", "code":"#98FB98"},
  {"color":"PaleTurquoise", "code":"#AFEEEE"},
  {"color":"PaleVioletRed", "code":"#DB7093"},
  {"color":"PeachPuff", "code":"#FFDAB9"},
  {"color":"Peru",  "code":"#CD853F"},
  {"color":"Pink",  "code":"#FFC0CB"},
  {"color":"PowderBlue",  "code":"#B0E0E6"},
  {"color":"Purple",  "code":"#800080"},
  {"color":"Red", "code":"#FF0000"},
  {"color":"RosyBrown", "code":"#BC8F8F"},
  {"color":"RoyalBlue", "code":"#4169E1"},
  {"color":"Salmon",  "code":"#FA8072"},
  {"color":"SandyBrown",  "code":"#F4A460"},
  {"color":"SeaGreen",  "code":"#2E8B57"},
  {"color":"Sienna",  "code":"#A0522D"},
  {"color":"Silver",  "code":"#C0C0C0"},
  {"color":"SkyBlue", "code":"#87CEEB"},
  {"color":"SpringGreen", "code":"#00FF7F"},
  {"color":"SteelBlue", "code":"#4682B4"},
  {"color":"Tan", "code":"#D2B48C"},
  {"color":"Teal",  "code":"#008080"},
  {"color":"Tomato",  "code":"#FF6347"},
  {"color":"Turquoise", "code":"#40E0D0"},
  {"color":"Violet",  "code":"#EE82EE"},
  {"color":"Wheat", "code":"#F5DEB3"},
  {"color":"WhiteSmoke",  "code":"#F5F5F5"},
  {"color":"Yellow",  "code":"#FFFF00"},
  {"color":"YellowGreen", "code":"#9ACD32"}
]
*/

// https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/obo_context.jsonld

var colors = {
  "AntiqueWhite":"#FAEBD7",
  "Aquamarine":"#7FFFD4",
  "Blue":"#0000FF",
  "BlueViolet":"#8A2BE2",
  "Brown":"#A52A2A",
  "CadetBlue":"#5F9EA0",
  "Chartreuse":"#7FFF00",
  "Chocolate":"#D2691E",
  "Coral":"#FF7F50",
  "CornflowerBlue":"#6495ED",
  "Crimson":"#DC143C",
  "Cyan":"#00FFFF",
  "DarkGoldenrod":"#B8860B",
  "DarkGray":"#A9A9A9",
  "DarkKhaki":"#BDB76B",
  "DarkOliveGreen":"#556B2F",
  "DarkOrange":"#FF8C00",
  "DarkOrchid":"#9932CC",
  "DarkRed":"#8B0000",
  "DarkSeaGreen":"#8FBC8F",
  "DarkTurquoise":"#00CED1",
  "DeepPink":"#FF1493",
  "DeepSkyBlue":"#00BFFF",
  "DodgerBlue":"#1E90FF",
  "FireBrick":"#B22222",
  "Gold":"#FFD700",
  "Goldenrod":"#DAA520",
  "Green":"#008000",
  "GreenYellow":"#ADFF2F",
  "HotPink":"#FF69B4",
  "IndianRed":"#CD5C5C",
  "Ivory":"#FFFFF0",
  "Khaki":"#F0E68C",
  "Lavender":"#E6E6FA",
  "LawnGreen":"#7CFC00",
  "LemonChiffon":"#FFFACD",
  "LightCyan":"#E0FFFF",
  "LightGoldenrodYellow":"#FAFAD2",
  "LightGreen":"#90EE90",
  "LightPink":"#FFB6C1",
  "LightSalmon":"#FFA07A",
  "LightSeaGreen":"#20B2AA",
  "LightSteelBlue":"#B0C4DE",
  "Lime":"#00FF00",
  "LimeGreen":"#32CD32",
  "Magenta":"#FF00FF",
  "Maroon":"#800000",
  "MediumAquamarine":"#66CDAA",
  "MediumPurple":"#9370DB",
  "MediumSeaGreen":"#3CB371",
  "MediumSlateBlue":"#7B68EE",
  "MediumSpringGreen":"#00FA9A",
  "MediumTurquoise":"#48D1CC",
  "NavajoWhite":"#FFDEAD",
  "Olive":"#808000",
  "OliveDrab":"#6B8E23",
  "Orange":"#FFA500",
  "OrangeRed":"#FF4500",
  "Orchid":"#DA70D6",
  "PaleGoldenrod":"#EEE8AA",
  "PaleGreen":"#98FB98",
  "PaleTurquoise":"#AFEEEE",
  "PaleVioletRed":"#DB7093",
  "PeachPuff":"#FFDAB9",
  "Peru":"#CD853F",
  "Pink":"#FFC0CB",
  "PowderBlue":"#B0E0E6",
  "Purple":"#800080",
  "Red":"#FF0000",
  "RosyBrown":"#BC8F8F",
  "RoyalBlue":"#4169E1",
  "Salmon":"#FA8072",
  "SandyBrown":"#F4A460",
  "SeaGreen":"#2E8B57",
  "Sienna":"#A0522D",
  "Silver":"#C0C0C0",
  "SkyBlue":"#87CEEB",
  "SpringGreen":"#00FF7F",
  "SteelBlue":"#4682B4",
  "Tan":"#D2B48C",
  "Teal":"#008080",
  "Tomato":"#FF6347",
  "Turquoise":"#40E0D0",
  "Violet":"#EE82EE",
  "Wheat":"#F5DEB3",
  "WhiteSmoke":"#F5F5F5",
  "Yellow":"#FFFF00",
  "YellowGreen":"#9ACD32"
}

var edge_color_mapping = {
  "owl":  {"color":"Gold"},
  "oboInOwl": {"color":"Gold"},

  // Miscellaneous ontologies
  "SIO":        {"color":"AntiqueWhite"},
  "NDF-RT":     {"color":"Aquamarine"},
  "EFO":        {"color":"Yellow"},
  "MESH":       {"color":"Coral"},
  "APOLLO_SV":  {"color":"Cyan"},
  "sep":        {"color":"LawnGreen"},
  "vcard":      {"color":"OrangeRed"},
  "ExO":        {"color":"HotPink"},
  "bibo":       {"color":"OrangeRed"},
  "typon":      {"color":"Orchid"},
  "sct":        {"color":"DodgerBlue"},
  "vcf":        {"color":"SandyBrown"},
  "hancestro":  {"color":"SandyBrown"},
  
  // OBOFOUNDRY ONTOLOOGIES
  "AAO":        {"color":"AntiqueWhite"},
  "ADW":        {"color":"Aquamarine"},
  "AEO":        {"color":"BlueViolet"},
  "AERO":       {"color":"BlueViolet"},
  "AGRO":       {"color":"Cyan"},
  "APO":        {"color":"CadetBlue"},
  "ARO":        {"color":"Chartreuse"},
  "ATO":        {"color":"Chocolate"},
  "BCGO":       {"color":"Coral"},
  "BCO":        {"color":"CornflowerBlue"},
  "BFO":        {"color":"Gold"},
  "BILA":       {"color":"Cyan"},
  "BOOTSTREP":  {"color":"DarkGoldenrod"},
  "BSPO":       {"color":"DarkGray"},
  "BTO":        {"color":"DarkKhaki"},
  "CARO":       {"color":"Khaki"},
  "CDAO":       {"color":"DarkOrange"},
  "CEPH":       {"color":"DarkOrchid"},
  "CHEBI":      {"color":"Khaki"},
  "CHEMINF":    {"color":"DarkSeaGreen"},
  "CHMO":       {"color":"DarkTurquoise"},
  "CIO":        {"color":"DeepPink"},
  "CL":         {"color":"DeepSkyBlue"},
  "CLO":        {"color":"DodgerBlue"},
  "CMF":        {"color":"FireBrick"},
  "CMO":        {"color":"Gold"},
  "CRO":        {"color":"Goldenrod"},
  "CTENO":      {"color":"Green"},
  "CVDO":       {"color":"GreenYellow"},
  "DC_CL":      {"color":"HotPink"},
  "DDANAT":     {"color":"IndianRed"},
  "DDPHENO":    {"color":"Ivory"},
  "DIDEO":      {"color":"Khaki"},
  "DINTO":      {"color":"Lavender"},
  "DOID":       {"color":"LawnGreen"},
  "DRON":       {"color":"LemonChiffon"},
  "DUO":        {"color":"LightCyan"},
  "ECO":        {"color":"LightGoldenrodYellow"},
  "ECOCORE":    {"color":"LightGreen"},
  "EHDA":       {"color":"LightPink"},
  "EHDAA":      {"color":"LightSalmon"},
  "EHDAA2":     {"color":"LightSeaGreen"},
  "EMAP":       {"color":"LightSteelBlue"},
  "EMAPA":      {"color":"Lime"},
  "ENVO":       {"color":"LimeGreen"},
  "EO":         {"color":"Magenta"},
  "EPO":        {"color":"Maroon"},
  "ERO":        {"color":"MediumAquamarine"},
  "EUPATH":     {"color":"MediumPurple"},
  "EV":         {"color":"MediumSeaGreen"},
  "EXO":        {"color":"MediumSlateBlue"},
  "FAO":        {"color":"MediumSpringGreen"},
  "FBSP":       {"color":"MediumTurquoise"},
  "FBbi":       {"color":"NavajoWhite"},
  "FBbt":       {"color":"Olive"},
  "FBcv":       {"color":"OliveDrab"},
  "FBdv":       {"color":"Orange"},
  "FIX":        {"color":"OrangeRed"},
  "FLOPO":      {"color":"Orchid"},
  "FLU":        {"color":"PaleGoldenrod"},
  "FMA":        {"color":"PaleGreen"},
  "FOODON":     {"color":"PaleTurquoise"},
  "FYPO":       {"color":"PaleVioletRed"},
  "GAZ":        {"color":"PeachPuff"},
  "GENEPIO":    {"color":"Peru"},
  "GENO":       {"color":"Pink"},
  "GEO":        {"color":"PowderBlue"},
  "GO":         {"color":"PowderBlue"},
  "GRO":        {"color":"Red"},
  "HABRONATTUS":  {"color":"RosyBrown"},
  "HANCESTRO":  {"color":"SandyBrown"},
  "HAO":        {"color":"Salmon"},
  "HOM":        {"color":"SandyBrown"},
  "HP":         {"color":"PeachPuff"},
  "HSAPDV":     {"color":"Sienna"},
  "IAO":        {"color":"Silver"},
  "ICO":        {"color":"SkyBlue"},
  "IDO":        {"color":"SpringGreen"},
  "IDOMAL":     {"color":"SteelBlue"},
  "IEV":        {"color":"Tan"},
  "IMR":        {"color":"Teal"},
  "INO":        {"color":"Tomato"},
  "IPR":        {"color":"Turquoise"},
  "KISAO":      {"color":"Violet"},
  "LIPRO":      {"color":"Wheat"},
  "LOGGERHEAD": {"color":"WhiteSmoke"},
  "MA":         {"color":"Yellow"},
  "MAMO":       {"color":"YellowGreen"},
  "MAO":        {"color":"AntiqueWhite"},
  "MAT":        {"color":"Aquamarine"},
  "MF":         {"color":"Blue"},
  "MFMO":       {"color":"BlueViolet"},
  "MFO":        {"color":"Brown"},
  "MFOEM":      {"color":"CadetBlue"},
  "MFOMD":      {"color":"Chartreuse"},
  "MI":         {"color":"Chocolate"},
  "MIAPA":      {"color":"Coral"},
  "MICRO":      {"color":"CornflowerBlue"},
  "MIRNAO":     {"color":"Crimson"},
  "MIRO":       {"color":"Cyan"},
  "MMO":        {"color":"DarkGoldenrod"},
  "MMUSDV":     {"color":"DarkGray"},
  "MO":         {"color":"DarkKhaki"},
  "MOD":        {"color":"DarkOliveGreen"},
  "MONDO":      {"color":"DarkOrange"},
  "MOP":        {"color":"DarkOrchid"},
  "MP":         {"color":"DarkRed"},
  "MPATH":      {"color":"DarkSeaGreen"},
  "MPIO":       {"color":"DarkTurquoise"},
  "MRO":        {"color":"DeepPink"},
  "MS":         {"color":"DeepSkyBlue"},
  "NBO":        {"color":"DodgerBlue"},
  "NCBITaxon":  {"color":"Ivory"},
  "NCIT":       {"color":"Gold"},
  "NCRO":       {"color":"Goldenrod"},
  "NIF_CELL":   {"color":"Green"},
  "NIF_DYSFUNCTION":  {"color":"GreenYellow"},
  "NIF_GROSSANATOMY": {"color":"HotPink"},
  "NMR":        {"color":"IndianRed"},
  "OAE":        {"color":"Ivory"},
  "OARCS":      {"color":"Khaki"},
  "OBA":        {"color":"Lavender"},
  "OBCS":       {"color":"LawnGreen"},
  "OBI":        {"color":"LemonChiffon"},
  "OBIB":       {"color":"LightCyan"},
  "OBO_REL":    {"color":"LightGoldenrodYellow"},
  "OGG":        {"color":"LightGreen"},
  "OGI":        {"color":"LightPink"},
  "OGMS":       {"color":"LightSalmon"},
  "OGSF":       {"color":"LightSeaGreen"},
  "OHD":        {"color":"LightSteelBlue"},
  "OHMI":       {"color":"Lime"},
  "OLATDV":     {"color":"LimeGreen"},
  "OMIABIS":    {"color":"Magenta"},
  "OMIT":       {"color":"Maroon"},
  "OMP":        {"color":"MediumAquamarine"},
  "OMRSE":      {"color":"MediumPurple"},
  "ONTONEO":    {"color":"MediumSeaGreen"},
  "OOSTT":      {"color":"MediumSlateBlue"},
  "OPL":        {"color":"MediumSpringGreen"},
  "OVAE":       {"color":"MediumTurquoise"},
  "PAO":        {"color":"MediumTurquoise"},
  "PATO":       {"color":"GreenYellow"},
  "PCO":        {"color":"Orange"},
  "PDRO":       {"color":"Orange"},
  "PDUMDV":     {"color":"OrangeRed"},
  "PD_ST":      {"color":"Orchid"},
  "PECO":       {"color":"PaleGoldenrod"},
  "PGDSO":      {"color":"PaleGreen"},
  "PLANA":      {"color":"PaleTurquoise"},
  "PLO":        {"color":"PaleVioletRed"},
  "PO":         {"color":"PeachPuff"},
  "PORO":       {"color":"Peru"},
  "PPO":        {"color":"Pink"},
  "PR":         {"color":"PowderBlue"},
  "PROPREO":    {"color":"Purple"},
  "PW":         {"color":"Red"},
  "RESID":      {"color":"RosyBrown"},
  "REX":        {"color":"RoyalBlue"},
  
  "REO":        {"color":"RoyalBlue"}, //???

  "RNAO":       {"color":"Salmon"},
  "RO":         {"color":"SandyBrown"},
  "RS":         {"color":"SeaGreen"},
  "RXNO":       {"color":"Sienna"},
  "SAO":        {"color":"Silver"},
  "SBO":        {"color":"SkyBlue"},
  "SEP":        {"color":"SpringGreen"},
  "SEPIO":      {"color":"SteelBlue"},
  "SIBO":       {"color":"Tan"},
  "SO":         {"color":"Teal"},
  "SOPHARM":    {"color":"Tomato"},
  "SPD":        {"color":"Turquoise"},
  "STATO":      {"color":"Violet"},
  "SWO":        {"color":"Wheat"},
  "SYMP":       {"color":"WhiteSmoke"},
  "TADS":       {"color":"Yellow"},
  "TAHE":       {"color":"YellowGreen"},
  "TAHH":       {"color":"AntiqueWhite"},
  "TAO":        {"color":"Aquamarine"},
  "TAXRANK":    {"color":"Blue"},
  "TGMA":       {"color":"BlueViolet"},
  "TO":         {"color":"Brown"},
  "TRANS":      {"color":"CadetBlue"},
  "TTO":        {"color":"Chartreuse"},
  "UBERON":     {"color":"Chocolate"},
  "UO":         {"color":"Coral"},
  "UPHENO":     {"color":"CornflowerBlue"},
  "VARIO":      {"color":"Crimson"},
  "VHOG":       {"color":"Cyan"},
  "VO":         {"color":"DarkGoldenrod"},
  "VSAO":       {"color":"DarkGray"},
  "VT":         {"color":"DarkKhaki"},
  "VTO":        {"color":"DarkOliveGreen"},
  "WBBT":       {"color":"DarkOrange"},
  "WBLS":       {"color":"DarkOrchid"},
  "WBPhenotype":  {"color":"DarkRed"},
  "XAO":        {"color":"DarkSeaGreen"},
  "XCO":        {"color":"DarkTurquoise"},
  "XL":         {"color":"DeepPink"},
  "YPO":        {"color":"DeepSkyBlue"},
  "ZEA":        {"color":"DodgerBlue"},
  "ZECO":       {"color":"FireBrick"},
  "ZFA":        {"color":"Gold"},
  "ZFS":        {"color":"YellowGreen"}
}

layout = {

  "owl:Thing": {"x": -1600,    "y": -1600,  "color": ""},
  "oboInOwl:ObsoleteClass": 
                 {"x": -2300, "y": -2300, "color": ""},

  "BFO:0000001": {"x": -486,  "y": -116,  "color": null         }, // entity
  "BFO:0000002": {"x": 120,   "y": -264,  "color": "Green"      }, //  continuant
  "BFO:0000004": {"x": 146,   "y": 193,   "color": "Lime"       }, //    independent continuant
  "BFO:0000040": {"x": -3,    "y": 475,   "color": "GreenYellow"}, //      material entity
  "BFO:0000024": {"x": 164,   "y": 571,   "color": null         }, //        fiat object part
  "BFO:0000030": {"x": -302,  "y": 450,   "color": null         }, //        object
  "BFO:0000027": {"x": -100,   "y": 650,  "color": null         }, //        object aggregate
  "BFO:0000141": {"x": 553,   "y": 362,   "color": null         }, //      immaterial entity
  "BFO:0000029": {"x": 537,   "y": 435,   "color": "LemonChiffon"}, //        site
  "BFO:0000006": {"x": 755,   "y": 724,   "color": null         }, //        spatial region
  "BFO:0000018": {"x": 700,   "y": 812,   "color": null         }, //          0d
  "BFO:0000026": {"x": 857,   "y": 806,   "color": null         }, //          1d
  "BFO:0000009": {"x": 782,   "y": 853,   "color": null         }, //          2d
  "BFO:0000028": {"x": 858,   "y": 716,   "color": null         }, //          3d
  "BFO:0000140": {"x": 833,   "y": 265,   "color": null         }, //      continuant fiat boundary   
  "BFO:0000147": {"x": 833,   "y": 169,   "color": null         }, //        0d
  "BFO:0000142": {"x": 932,   "y": 196,   "color": null         }, //        1d
  "BFO:0000146": {"x": 937,   "y": 295,   "color": null         }, //        2d
  "BFO:0000031": {"x": 600,   "y": -305,  "color": "Silver"     }, //    generically dependent continuant
  "BFO:0000020": {"x": 96,    "y": -747,  "color": "DarkSeaGreen"}, //    specifically dependent continuant
  "BFO:0000017": {"x": 135,   "y": -1156, "color": "OliveDrab"  }, //      realizable entity
  "BFO:0000023": {"x": 166,   "y": -1238, "color": null         }, //        role
  "BFO:0000016": {"x": 177,   "y": -1402, "color": null         }, //        disposition
  "BFO:0000034": {"x": 201,   "y": -1518, "color": null         }, //          function
  "BFO:0000019": {"x": 268,   "y": -845,  "color": "Olive"      }, //      quality
  "BFO:0000145": {"x": 373,   "y": -900,  "color": null         }, //        relational quality

  "BFO:0000003": {"x": -1041, "y": -62,   "color": "Blue"       }, //  occurant
  "BFO:0000015": {"x": -1353, "y": -89,   "color": "DeepSkyBlue"}, //    process
  "BFO:0000144": {"x": -1469, "y": 50,    "color": null         }, //      process profile
  "BFO:0000182": {"x": -1445, "y": -265,  "color": null         }, //      history
  "BFO:0000035": {"x": -1118,  "y": -510, "color": "DodgerBlue" }, //    process boundary
  "BFO:0000011": {"x": -817,  "y": -100,  "color": "BlueViolet" }, //    spatial temporal region
  "BFO:0000008": {"x": -1118,  "y": 220,  "color": "RoyalBlue"  }, //    temporal region
  "BFO:0000148": {"x": -1006, "y": 327,   "color": null         }, //       0d
  "BFO:0000038": {"x": -1298, "y": 274,   "color": null         }, //       1d
  "BFO:0000005": {"x": -2350, "y": -2350, "color": null         }  //       deprecated
}
